### ISSUE TITLE
plugins.ymlの形式変更

### ISSUE THREAD

**Issue by fujit4** [fujit4/ttvpack#1]
plugins.ymlの形式を変えて、設計を見直したい。
やりたいことは

plugins.ymlの形式

現状
```yml
 start:
   - repo: username/repo1
     tag: v1.0.0
   - repo: username/repo2
     tag: main

 opt:
   - repo: username/repo3
     tag: v2.1.0
```

変更後
```yml
 start:
   - repo: username/repo1
     tag: v1.0.0
     url: https://github.com/username/repo1/archive/refs/tags/v1.0.0.zip
   - repo: username/repo2
     branch: main
     url: https://github.com/username/repo2/archive/refs/heads/main.zip

 opt:
   - repo: username/repo3
     branch: main
     url: https://github.com/username/repo3/archive/refs/heads/main.zip
```

これにより、sync処理では、urlをもとにダウンロード処理を行う。
ディレクトリ名は「repoのBase-branch or tag」とする。branchとtagが両方指定ある場合、tag優先にする。

add処理では、urlだけを渡すと、分解してrepoとbranchとtagを解析して、記載してくれる。
一方でgithub以外の場所のものも手作業で入れればよいだけになる。
